#!/usr/bin/env python
"""Reproduce the social-force crowd robustness experiment (Table 6 / Fig. 11).

Re-runs the stress-condition main comparison (44 C, dense; 5 envs x 24 missions)
with per-edge crowd density generated by a Helbing social-force pedestrian
simulation instead of the synthetic hand-authored field. The thermal model and
planner are unchanged; only the crowd source differs.

Usage:  PYTHONPATH=. python scripts/run_social_force.py
Writes: results/results_social_force.json
"""
import os, json, types
import numpy as np
from scipy.stats import ranksums
from earp_gait import model, social_force
from earp_gait.model import Robot
from earp_gait.planner import (Surrogate, Mission, plan_earp, plan_fixed_gait,
                               plan_reactive, plan_thermal_reactive, evaluate_plan, ACOPlanner)

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "..", "results", "results_social_force.json")


def make_missions(env, n, seed, alpha0, T_amb, base_density, surge=0.0):
    rng = np.random.default_rng(seed); N = env.n_nodes
    D = np.linalg.norm(env.pos[:, None, :] - env.pos[None, :, :], axis=2)
    ms = []
    while len(ms) < n:
        s = int(rng.integers(N)); far = np.argsort(D[s])[-N // 3:]; dst = int(rng.choice(far))
        if s == dst: continue
        ms.append(Mission(source=s, dest=dst, alpha0=alpha0, T_amb=T_amb,
                          base_density=base_density,
                          surge=float(rng.uniform(0, surge)) if surge else 0.0))
    return ms


def naive(env, rob, m, sur, seed):
    return ACOPlanner(rob, env, sur, seed=seed, use_surrogate=True, use_safety=False,
                      use_elite=False, thermal_aware=False).solve(m)


def summarize(rs):
    fe = [r["feasible"] for r in rs]
    E = [r["energy"] for r in rs if r["feasible"] and np.isfinite(r["energy"])]
    fit = [r["fitness"] for r in rs]; tf = [r["thermal_fail"] for r in rs]
    return dict(succ=100 * np.mean(fe), E=float(np.nanmean(E)), Esd=float(np.nanstd(E)),
                fit=float(np.mean(fit)), therm=100 * np.mean(tf),
                fitlist=[f for f in fit if np.isfinite(f)])


def main(n_envs=5, n_missions=24, n_agents=140):
    methods = ["EARP-Gait", "Thermal-reactive", "Fixed-gait", "Reactive", "DDTA-ACO (naive)"]
    res = {m: [] for m in methods}
    for ei in range(n_envs):
        env = model.Environment(n_nodes=40, seed=ei)
        rob = Robot(); sur = Surrogate().fit(rob, env, np.random.default_rng(100 + ei), n=3000)
        snaps, _ = social_force.build_density_snapshots(env, n_agents=n_agents, seed=200 + ei,
                                                        warmup=40, n_snapshots=12, steps_between=6)
        sfd = social_force.SocialForceDensity(snaps, snapshot_period_s=30.0)
        env.crowd_density = types.MethodType(
            lambda self, i, j, t, base_density=0.3, surge=0.0: sfd(i, j, t, base_density, surge), env)
        ms = make_missions(env, n_missions, seed=1000 + ei, alpha0=0.55,
                           T_amb=44, base_density=0.6, surge=0.2)
        for k, m in enumerate(ms):
            _, _, r, _ = plan_earp(robot=rob, env=env, mission=m, surrogate=sur, seed=k + 1)
            res["EARP-Gait"].append(r)
            tr = plan_thermal_reactive(rob, env, m)
            res["Thermal-reactive"].append(evaluate_plan(rob, env, m, *tr) if tr
                                           else {"feasible": False, "energy": np.nan, "fitness": 10.0, "thermal_fail": False})
            fg = plan_fixed_gait(rob, env, m)
            res["Fixed-gait"].append(evaluate_plan(rob, env, m, *fg) if fg
                                     else {"feasible": False, "energy": np.nan, "fitness": 10.0, "thermal_fail": False})
            res["Reactive"].append(evaluate_plan(rob, env, m, *plan_reactive(rob, env, m)))
            _, _, r2, _ = naive(env, rob, m, sur, seed=k + 1)
            res["DDTA-ACO (naive)"].append(r2)
        print(f"env {ei+1}/{n_envs} done")

    S = {m: summarize(res[m]) for m in methods}
    earp = S["EARP-Gait"]["fitlist"]
    out = {"condition": "stress_44C_dense_socialforce", "n_envs": n_envs, "n_missions": n_missions,
           "T_amb": 44, "crowd_model": "Helbing social-force [15]", "results": {}}
    print("\n=== Social-force crowd robustness (44 C, dense) ===")
    for m in methods:
        s = S[m]
        p = None if m == "EARP-Gait" else float(ranksums(earp, s["fitlist"]).pvalue)
        out["results"][m] = {k: v for k, v in s.items() if k != "fitlist"}
        out["results"][m]["p_vs_earp"] = p
        print(f"  {m:18s} succ={s['succ']:5.1f} E={s['E']:5.2f} fit={s['fit']:4.2f} "
              f"therm={s['therm']:5.1f} " + ("" if p is None else f"p={p:.2e}"))
    json.dump(out, open(OUT, "w"), indent=2)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
